[project]
name = "cj12"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["starlette>=0.47.2", "uvicorn>=0.35.0"]

[dependency-groups]
dev = ["pre-commit>=4.2.0"]

[tool.ruff]
lint.select = ["ALL"]
lint.ignore = ["D"]

[tool.pyright]
typeCheckingMode = "off"
