[project]
name = "cj12"
version = "0.1.0"
requires-python = ">=3.13"

[dependency-groups]
dev = ["pre-commit>=4.2.0", "pytest>=8.4.1"]

[tool.ruff]
lint.select = ["ALL"]
lint.ignore = ["D"]
lint.per-file-ignores = { "tests/**/*.py" = ["S101", "PLR2004"] }
